# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'astroanthro'

#google-ID: 'UA-112060364-2'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Team', folder: 'pages', file: 'team.html'}
- {name: 'Posts', folder: 'pages', file: 'posts.html'}
- {name: 'Articles', folder: 'pages', file: 'resources.html'}
- {name: 'Videos', folder: 'pages', file: 'videos.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}
- {name: 'Science Tourist', folder: 'pages', file: 'science-tourist.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/astroanthro'}
#- {icon: 'facebook', link: 'https://www.facebook.com/astroanthro'}
#- {icon: 'instagram', link: 'https://instagram.com/astroanthro'}
- {icon: 'envelope', link: 'mailto:jholbrook@uwc.ac.za'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Read more'

post_date_prefix: 'Written on'
